language: ruby

rvm:
  - 2.2.5
  - 2.3.1
  - jruby
  - rbx

gemfile:
  - Gemfile
  - gemfiles/Gemfile.activesupport-4
  - gemfiles/Gemfile.activesupport-5

matrix:
  allow_failures:
  - rvm: jruby
    gemfile: Gemfile
  - rvm: jruby
    gemfile: gemfile/Gemfile.activesupport-5
